apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-06bc012cafb9a1c52,subnet-0c2f194ea77f28854
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000s
